{% set name = "jrsync" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jrsync-{{ version }}.tar.gz
  sha256: 35e7c87c5fff68ecb8ed5a60c7e6e85c34d6a57eddbdf293ac12a0b7721cf535

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.10.0,<4.0.0
    - pydantic >=2.8.2,<3.0.0
    - pyyaml >=6.0.1,<7.0.0
    - pytest >=8.3.2,<9.0.0

test:
  imports:
    - jrsync
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/jrsync/
  summary: JSON Configurable wrapper on unix rsync
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anto6715
